# Załaduj domyślną konfigurację Nginx
include /etc/nginx/mime.types;
default_type application/octet-stream;

# Serwer HTTP
server {
    listen 80;
    server_name udanyrejs.kamilzeglen.pl;

    # Przekierowanie HTTP na HTTPS
    return 301 https://$host$request_uri;
}

# Serwer HTTPS
server {
    listen 8006 ssl;
    server_name udanyrejs.kamilzeglen.pl;

    # Ścieżki do certyfikatu SSL
    ssl_certificate /etc/letsencrypt/live/npm-9/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/npm-9/privkey.pem;

    # Inne opcje SSL (opcjonalnie)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256';
    ssl_prefer_server_ciphers off;

    # Lokalizacja aplikacji
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
