import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedAddCompanies1733937034220 implements MigrationInterface {
  name = 'SeedAddCompanies1733937034220';

  public companies = [
    {
      id: '841d1a1b-09f4-499c-9f99-2836d32b22c2',
      name: 'MSC Cruises',
      key: 'MSC',
      description:
        'MSC Cruises powstało w 1960 roku w Neapolu. Jest liderem na rynku rejsów po Morzu Śródziemnym, pływając po tym obszarze przez cały rok. Dodatkowo oferuje szeroki wybór tras sezonowych jak: Europa Północna, rejsy przez Atlantyk, Karaiby, Ameryka Północna i Południowa, Kanada, Ocean Indyjski, Zachodnia i Południowa Afryka. \n\nFirma jest całkowicie europejska, ale posiada biura na całym świecie. Nowoczesna flota MSC to kilkanaście statków. Każdy z nich charakteryzuje się eleganckimi, stonowanymi wnętrzami, dbałością o szczegóły oraz włoską gościnnością którą można się cieszyć podczas rejsu. Na uwagę zasługują innowacyjne statki MSC Seaside i MSC Seaview, które wyróżniają się zewnętrzną promenadą biegnącą wokół statku. Na jej poziomie znajdują się bary i restauracje, co pozwala cieszyć się czasem na świeżym powietrzu. \n\nArmator stale powiększa flotę, inwestując w nowoczesne technologie i przyjazne środowisku rozwiązania. Jednocześnie dba o starsze jednostki, regularnie je remontując.',
      priceIncludes: JSON.stringify([
        'zakwaterowanie w kabinie wybranej kategorii',
        'wyżywienie - 3 główne posiłki, przekąski między posiłkami',
        'napoje serwowane do śniadania i w bufetach samoobsługowych',
        'napiwki dla obsługi (kwota zależy od długości rejsu)',
        'serwis bagażowy podczas wejścia i zejścia ze statku',
        'serwis kabinowy',
        'korzystanie ze wszystkich urządzeń sportowo-rekreacyjnych znajdujących się na pokładzie statku (basen, jacuzzi, sala fitness, itp.)',
        'udział we wszystkich imprezach organizowanych na statku (przedstawienia w teatrze, koncerty, programy animacyjne itp.)',
        'opłaty portowe',
      ]),
      priceExcludes: JSON.stringify([
        'kosztów dojazdu do portu',
        'ewentualnych noclegów w hotelu przed/po rejsie i transferów',
        'wycieczek fakultatywnych w trakcie rejsu',
        'korzystania z barów, mini baru w kabinie oraz napojów zamawianych w restauracji',
        'korzystania z punktów usługowych (fryzjer, pralnia, fotograf, salon piękności i odnowy biologicznej, internet)',
        'serwis kabinowy',
        'wydatków osobistych',
        'ubezpieczenia KL, NNW i bagaż',
        'kosztów wiz (tam gdzie wymagane)',
      ]),
    },
    {
      id: '83a07c58-5b60-4e2e-81d1-24689ad762a8',
      name: 'AIDA Cruises',
      key: 'AIDA',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '1e554f55-e1ab-40cf-b69c-59d92f2cd5dc',
      name: 'Costa Cruises',
      key: 'COSTA',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '29d58cf9-56e8-4bc6-af61-22412f4390ce',
      name: 'TUI Cruises',
      key: 'TUI',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'ac589100-cd6f-4d0a-8da3-81e3654c211f',
      name: 'Norwegian Cruise Line',
      key: 'NCL',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'e676773f-d20d-4ffd-baa0-5e0248738605',
      name: 'Royal Caribbean',
      key: 'ROYAL',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'dc8cb607-cdab-4564-82d9-fbeb70162943',
      name: 'AmaWaterways',
      key: 'AMA',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'a93ab6e0-02f0-471e-b660-0883d789dbb1',
      name: 'American Cruise Lines',
      key: 'ACL',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '217cfd91-1957-4d40-8455-37031d8f77be',
      name: 'Aqua Expeditions',
      key: 'AQUA',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'c7425461-8a71-465c-8094-3fe1521c4289',
      name: 'Aranui Cruises',
      key: 'ARANUI',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'e6ac7a3a-3590-4ede-9342-b7dd9a23fab5',
      name: 'Azamara Club Cruises',
      key: 'AZAMARA',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '602e8b52-b110-4c1f-b0f7-dc3c3e0ac91b',
      name: 'Carnival Cruise Lines',
      key: 'CARNIVAL',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '519d59e9-7158-4751-b909-ea8416e7802c',
      name: 'Celebrity Cruises',
      key: 'CELEBRITY',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'beeb83a2-d0c7-406c-a8c7-7274f6cedbd8',
      name: 'Celestyal Cruises',
      key: 'CELESTYAL',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '8ea08d92-a4ca-49a8-8478-5b1bd5087d71',
      name: 'CroisiEurope',
      key: 'CE',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '4db2c8d3-183e-48fd-a63f-aeef73fb38d5',
      name: 'Crystal Cruises',
      key: 'CRYSTAL',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '7d4f8375-d316-434c-a8e0-888f93129f30',
      name: 'Cunard',
      key: 'CUNARD',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '5fb3c916-d705-4c36-b6d7-316d5e159055',
      name: 'Disney Cruise Line',
      key: 'DISNEY',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'f6686c02-d5ca-4796-8e82-9b97e46b000b',
      name: 'Elixir Boutique Cruises',
      key: 'ELIXIR',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'aa3b2f37-d5a6-438e-a18b-035d4488ecc9',
      name: 'Explora Journeys',
      key: 'EXPLORA',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '42dc5a0b-3dbf-4123-9b54-d2bc3d00138b',
      name: 'Hapag-Lloyd Cruises',
      key: 'HLC',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '2c2f86e6-87fc-4c01-8d64-281b7c62a7e1',
      name: 'Hapag-Lloyd Expedition Cruises',
      key: 'HLEC',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'ffa93f63-476a-401e-b6eb-133760ae94d3',
      name: 'Holland America Line',
      key: 'HAL',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '27f3d6cf-412a-44b0-a581-6b23de88854f',
      name: 'Hurtiguten Expeditions',
      key: 'HE',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'bb7554e2-e23f-4eec-8bff-db0c07f9fb8f',
      name: 'Katarina Line Cruises',
      key: 'KLC',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '2b899885-8aae-4e6a-b674-07c0a4122426',
      name: 'Lotus Cruises',
      key: 'LC',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '194f4545-5f34-4606-ac08-73b4ab8f267b',
      name: 'Nicko Cruises',
      key: 'NC',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '7f831b42-9331-42bb-aea1-39a60565c3b7',
      name: 'Oceania Cruises',
      key: 'OC',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'df5499cf-6faf-4d52-9640-ca62c8d9ff92',
      name: 'P&O Cruises',
      key: 'POC',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '728ea8f8-beb4-4c88-81be-1974b9ca5f9b',
      name: 'Pandaw River Expeditions',
      key: 'PRE',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'cdf64bb3-a3b4-4464-91c3-461e8a1eb08a',
      name: 'Paul Gauguin Cruises',
      key: 'PGC',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '097315d6-f9c0-404a-9a0b-14b537b08bf6',
      name: 'Ponant - Yacht Cruises & Expeditions',
      key: 'PONANT',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '3eeb4c10-bc9f-410e-9ab6-5af97e63a4b6',
      name: 'Princess Cruises',
      key: 'PRINCESS',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '4abe8bd5-21b7-4a5d-8573-00b0ed30a93e',
      name: 'Quark Expedition',
      key: 'QUARK',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'c5c8abbe-ba24-48ed-b9ba-1353eaaee9ce',
      name: 'Regent Seven Seas Cruises',
      key: 'RSSC',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '068453bc-a1f1-4d90-bbc6-6cd628b87c2d',
      name: 'Scubaspa Maldives',
      key: 'SM',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '3c99189a-c0b3-4c41-b55c-fd3affee1981',
      name: 'Seabourn',
      key: 'SEABOURN',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'b6f58781-900e-470a-a2d6-29e8f453dbfd',
      name: 'SeaDream Yacht Club',
      key: 'SEADREAN',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'aeeb6d26-d0d6-4b68-ab10-71049dce6512',
      name: 'Silversea Cruises',
      key: 'SILVERSEA',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'c8c60a7c-e0f8-4f09-9c20-5acd11e0e45d',
      name: 'Star Clippers',
      key: 'STAR',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'f73b6c34-b206-4d71-8edf-30faf4e987a5',
      name: 'The Ritz-Carlton Yacht Collection',
      key: 'RITZ',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '7d5e464a-835e-4c66-8aa9-37094d9c1761',
      name: 'Travelmarvel',
      key: 'TRAVELMARVEL',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '03a0da4b-5f92-4785-aa1a-7cf6fb5d542c',
      name: 'Uniworld Boutique River Cruises',
      key: 'UBRC',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'af1884f6-eb2a-43cd-87cf-0680bdfbb5da',
      name: 'Variety Cruises',
      key: 'VAARIETY',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'bc6d0c19-e1ab-4bde-86e4-9060cd5177e5',
      name: 'Viking Cruises',
      key: 'VIKING',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: '0a993515-7517-42cb-bc28-680398c43d87',
      name: 'Virgin Voyages',
      key: 'VIRGIN',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'bef147b5-7bf4-4491-af21-c0d03a201771',
      name: 'Windstar Cruises',
      key: 'WINDSTAR',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
    {
      id: 'd118026d-7c8d-4482-8103-11907a2d019d',
      name: 'Yasawa Princess',
      key: 'YASAWA',
      description: '',
      priceIncludes: '',
      priceExcludes: '',
    },
  ];

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const company of this.companies) {
      await queryRunner.query(
        `
    INSERT INTO "company" ("id", "name", "key", "description", "priceIncludes", "priceExcludes", "createdById", "updatedById")
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    ON CONFLICT ("id") DO NOTHING;
  `,
        [
          company.id,
          company.name,
          company.key,
          company.description || null,
          company.priceIncludes || null,
          company.priceExcludes || null,
          '12345678-3cf2-4e11-87c2-f6a75aa28f8d',
          '12345678-3cf2-4e11-87c2-f6a75aa28f8d',
        ],
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const company of this.companies) {
      await queryRunner.query(`
        DELETE FROM "company"
        WHERE "name" = '${company.name}'
      `);
    }
  }
}
