import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedAddShips1735169911932 implements MigrationInterface {
  name = 'SeedAddShips1735169911932';

  public ships = [
    {
      name: 'MSC Armonia',
      companyName: 'MSC Cruises',
      description:
        'Zbudowana w 2001 dla nieistniejącego już dziś armatora Festival Cruises jako MS European Vision. W tym samym roku została wyczarterowana na szczyt G8 w Genui jako bezpieczne miejsce spotkania światowych przywódców. Od 2004 roku we flocie MSC Cruises. Chociaż z zewnątrz MSC Armonia wygląda majestatycznie, w środku jest kameralna i bardzo przyjazna. Odnowiona w 2014 roku, we włoskim stylu i z elegancją, będącą znakiem firmowym MSC Cruises. Podczas renowacji dodano nowe kabiny z balkonem, powiększono restauracje oraz bufety. Wszystkie wnętrza zostały odnowione. Dla dzieci strefy zabaw wyposażone dzięki pomocy partnerów, takich jak Lego, Chicco i Namco. Powstał również basen z fontannami dla dzieci. Unowocześnione spa z większą przestrzenią na masaże.',
      yearBuilt: 2001,
      renovation: 2019,
      speed: 20,
      length: 275,
      width: 32,
      tonnage: '65 542',
      passengersDecks: 9,
      passengers: '2 679',
      crew: 721,
      currency: 'Euro',
      ImageFileURL:
        'https://rejsy4you.pl/public/upload/2019/03/18/msc_armonia_widok_statku_2_1.jpg',
    },
    {
      name: 'MSC Bellissima',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Divina',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Euribia',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Fantasia',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Grandiosa',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Lirica',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Magnifica',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Meraviglia',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Musica',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Opera',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Orchestra',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Poesia',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Preziosa',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Seascape',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Seashore',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Seaside',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Seaview',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Sinfonia',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Splendida',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC Virtuosa',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC World America',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MSC World Europa',
      companyName: 'MSC Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'AIDAbella',
      companyName: 'AIDA Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'AIDAblu',
      companyName: 'AIDA Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'AIDAcosma',
      companyName: 'AIDA Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'AIDAdiva',
      companyName: 'AIDA Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'AIDAluna',
      companyName: 'AIDA Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'AIDAmar',
      companyName: 'AIDA Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'AIDAnova',
      companyName: 'AIDA Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'AIDAperla',
      companyName: 'AIDA Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'AIDAprima',
      companyName: 'AIDA Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'AIDAsol',
      companyName: 'AIDA Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'AIDAstella',
      companyName: 'AIDA Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Costa Deliziosa',
      companyName: 'Costa Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Costa Diadema',
      companyName: 'Costa Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Costa Fascinosa',
      companyName: 'Costa Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Costa Favolosa',
      companyName: 'Costa Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Costa Fortuna',
      companyName: 'Costa Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Costa Pacifica',
      companyName: 'Costa Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Costa Serena',
      companyName: 'Costa Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Costa Smeralda',
      companyName: 'Costa Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Costa Toscana',
      companyName: 'Costa Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Aqua',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Bliss',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Breakaway',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Dawn',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Encore',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Epic',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Escape',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Gem',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Gateway',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Jade',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Jewel',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Joy',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Luna',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Pearl',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Prima',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Sky',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Spirit',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Star',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Sun',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Norwegian Viva',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Pride Of America',
      companyName: 'Norwegian Cruise Line',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Adventure of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Allure of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Anthem of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Brilliance of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Enchantment of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Explorer of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Freedom of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Grandeur of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Harmony of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Icon of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Independence of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Jewel of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Liberty of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Mariner of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Navigator of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Oasis of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Odyssey of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Ovation of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Quantum of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Radiance of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Rhapsody of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Serenade of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Spectrum of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Symphony of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Vision of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Voyager of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'Wonder of the Seas',
      companyName: 'Royal Caribbean',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MEIN SCHIFF 1',
      companyName: 'TUI Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MEIN SCHIFF 5',
      companyName: 'TUI Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
    {
      name: 'MEIN SCHIFF 6',
      companyName: 'TUI Cruises',
      description: '',
      yearBuilt: '',
      renovation: '',
      speed: '',
      length: '',
      width: '',
      tonnage: '',
      passengersDecks: '',
      passengers: '',
      crew: '',
      currency: '',
      ImageFileURL: '',
    },
  ];

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const ship of this.ships) {
      await queryRunner.query(`
      INSERT INTO "ship" (
        "id", 
        "name", 
        "companyId", 
        "description", 
        "yearBuilt", 
        "renovation", 
        "speed", 
        "length", 
        "width", 
        "tonnage", 
        "passengersDecks", 
        "passengers", 
        "crew", 
        "currency",
        "createdById", 
        "updatedById"
        )
      VALUES (
        uuid_generate_v4(),
        '${ship.name}',
        (SELECT "id" FROM "company" WHERE "name" = '${ship.companyName}'),
        '${ship.description.replace(/'/g, "''")}',
        ${ship.yearBuilt ? `'${ship.yearBuilt}'` : null},
        ${ship.renovation ? `'${ship.renovation}'` : null},
        ${ship.speed ? `'${ship.speed}'` : null},
        ${ship.length ? `'${ship.length}'` : null},
        ${ship.width ? `'${ship.width}'` : null},
        ${ship.tonnage ? `'${ship.tonnage.replace(/[^0-9]/g, '')}'` : null},
        ${ship.passengersDecks ? `'${ship.passengersDecks}'` : null},
        ${ship.passengers ? `'${ship.passengers.replace(/[^0-9]/g, '')}'` : null},
        ${ship.crew ? `'${ship.crew}'` : null},
        '${ship.currency}',
        '12345678-3cf2-4e11-87c2-f6a75aa28f8d',
        '12345678-3cf2-4e11-87c2-f6a75aa28f8d'
      );
    `);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const ship of this.ships) {
      await queryRunner.query(`
        DELETE FROM "ship"
        WHERE "name" = '${ship.name}' AND "companyId" = (
          SELECT "id" FROM "company" WHERE "name" = '${ship.companyName}'
        );
      `);
    }
  }
}
