services:
    udanyrejs-frontend:
        build:
            context: ./web
            dockerfile: Dockerfile
        container_name: udanyrejs-frontend
        restart: always
        networks:
            - nginx-proxy-manager_default
            - udanyrejs_default

    udanyrejs-backend:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: udanyrejs-backend
        env_file:
            - api/.env
        restart: always
        volumes:
            - ./files/OFFERS_IMAGES:/api/files/OFFERS_IMAGES
            - ./files/SHIPS_IMAGES:/api/files/SHIPS_IMAGES
            - ./files/COMPANIES_IMAGES:/api/files/COMPANIES_IMAGES
            - ./files/OFFERS_PDFS:/api/files/OFFERS_PDFS
        networks:
            - nginx-proxy-manager_default
            - postgres_default
            - udanyrejs_default

    udanyrejs-scraper:
        build:
            context: ./scraper
            dockerfile: Dockerfile
        container_name: udanyrejs-scraper
        env_file:
            - scraper/.env
        restart: always
        networks:
            - udanyrejs_default

networks:
    nginx-proxy-manager_default:
        external: true
    postgres_default:
        external: true
    udanyrejs_default:
        external: true
